# Generated by Django 5.2 on 2025-04-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='points_awarded',
            field=models.BooleanField(default=False, verbose_name='Đã cộng điểm'),
        ),
        migrations.AddField(
            model_name='booking',
            name='points_awarded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
