# Generated by Django 5.2 on 2025-04-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_points_awarded_booking_points_awarded_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'permissions': [('manage_booking', 'Can manage all bookings')], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
